<?php

namespace Tests\Feature\app\Http\Controllers;

use App\Models\User;
use Laravel\Lumen\Testing\DatabaseMigrations;
use Laravel\Lumen\Testing\TestCase;

class AuthControllerTest extends TestCase
{
    use DatabaseMigrations;
    /**
     * @inheritDoc
     */
    public function createApplication()
    {
        return require './bootstrap/app.php';
    }
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testUserShouldNotAuthenticateWithWrongProvider()
    {
        $payload = [
            'email' => 'italo@gmail.com',
            'password' => 'secret123'
        ];

        $request = $this->post(route('authenticate', ['provider' => 'provider-errado']), $payload);

        $request->assertResponseStatus(422);
        $request->seeJson(['errors' => ['main' => 'Wrong Provider']]);

    }

    public function testUserShouldBeDeniedIfNotRegirested()
    {
        $payload = [
            'email' => 'italo@gmail.com',
            'password' => 'secret123'
        ];

        $request = $this->post(route('authenticate', ['provider' => 'user']), $payload);
        $request->assertResponseStatus(401);
        $request->seeJson(['errors' => ['main' => 'Wrong Credentials']]);

    }

    public function testUserShouldSendWrongPassword()
    {
        $user = User::factory()->create();
        $payload = [
            'email' => $user->email,
            'password' => 'secret12'
        ];

        $request = $this->post(route('authenticate', ['provider' => 'user']), $payload);
        $request->assertResponseStatus(401);
        $request->seeJson(['errors' => ['main' => 'Wrong Password']]);

    }

    public function testUserCanAuthenticate()
    {
        $this->artisan('passport:install');
        $user = User::factory()->create();
        $payload = [
            'email' => $user->email,
            'password' => 'secret123'
        ];

        $request = $this->post(route('authenticate', ['provider' => 'user']), $payload);
        $request->assertResponseStatus(200);
        $request->seeJsonStructure(['acess_token', 'expires_at', 'provider']);
    }

}
